### PR TITLE
Add cmake support

### PR DESCRIPTION
**Pull request by anjohan**
I have added cmake support for building and installing. Additionally, it is now possible to use this in a cmake-based project with `add_subdirectory`.

Tested with cmake 3.12, with the compilers gfortran 8.2.1, ifort 18.0.1 and pgfortran 18.4.0.

None of the existing files have been touched (except README.md and .gitignore), so I hopefully haven't broken anything.

I have added CMakeLists.txt and cmake/source_list.cmake. I also added an example program to the README for good measure.

See the README for usage.

Feedback appreciated!

### CODE REVIEW

**Comment by scivision** [comment]
Thanks, I will take a look soon. this is a good addition for cmake users. If one doesn't want to copy a project into their repo or make a git submodule, cmake FetchContent works well, and is usually my first choice for external code.

**Comment by scivision** [comment]
Thanks for adding the FetchContent example. Yes, it does the same thing as Git submodule, but in a more abstract and perhaps less confusing way for end users. If I make a change to external libraries, these are reflected in the CMake generation step instead of having to have all users update their Git submodules and then CMake generation.  Two steps -> one step using FetchContent. As you may have noticed FetchContent is a higher-level form of ExternalProject.

**Comment by scivision** [comment]
It's also good that you listed the sources explicitly in a separate .cmake file. GLOB is tempting, but is an anti-pattern for modern, performant CMake.

**Comment by scivision** [comment]
I am working on this in branch "anjohan-master". I need to make it have "COMPONENTS" to better match Makefile behavior (only compiling needed functions e.g. double). No problem, thanks for the inspiration.

**Comment by anjohan** [comment]
> Thanks for adding the FetchContent example. Yes, it does the same thing as Git submodule, but in a more abstract and perhaps less confusing way for end users. If I make a change to external libraries, these are reflected in the CMake generation step instead of having to have all users update their Git submodules and then CMake generation. Two steps -> one step using FetchContent. As you may have noticed FetchContent is a higher-level form of ExternalProject.

I'm not a very experienced cmake user, so I had never even heard of FetchContent or ExternalProject - thank you for pointing these out!

> It's also good that you listed the sources explicitly in a separate .cmake file. GLOB is tempting, but is an anti-pattern for modern, performant CMake.

As a lazy person, I initially tried to just GLOB `la_*.f90` together with `f*_single_...f90`, but there are apparently some extra files which are not in use and not compilable (at least a couple of symmetric complex routines, probably erroneously autogenerated). The .cmake file is just regexed from the original makefile (fortunately).

> I am working on this in branch "anjohan-master". I need to make it have "COMPONENTS" to better match Makefile behavior (only compiling needed functions e.g. double). No problem, thanks for the inspiration.

Good idea!

I just added "the whole shebang", but I guess the compilation time can be reduced by a factor of 4-ish by only compiling one precision.

In the added .cmake, each unindented line starts a new precision, so I guess you could just split each "paragraph" into a separate variable (e.g. `single_sources`, `double_sources` etc.).

**Comment by scivision** [comment]
yes I'm making it so that Cmake starts inside SRC, to help avoid all those ${srcdir}/

**Comment by scivision** [comment]
merged in cb796ed

**Pull request closed without merging**
